version: '3.8'

services:
  mongo-db:
    image: mongo
    volumes:
      - /home/chocho/study/docker/react_nodejs/data:/data/db
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        http_proxy: http://70.10.15.10:8080
        https_proxy: http://70.10.15.10:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        http_proxy: http://70.10.15.10:8080
        https_proxy: http://70.10.15.10:8080
    ports:
      - '80:80'
