apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - image: backend:k8s
          name: container1
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: backend-configs
