apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1G
  hostPath:
    path: /home/chocho/study/docker/react_nodejs/pv
